batch_size: 64
accum_grad: 2
max_epoch: 200
patience: 20
val_scheduler_criterion:
- train
- loss
early_stopping_criterion:
- train
- loss
- min
# The initialization method for model parameters
init: xavier_uniform

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.3
    positional_dropout_rate: 0.3
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.3
    positional_dropout_rate: 0.3
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

e2e_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.01
scheduler: warmuplrreducelronplateau
scheduler_conf:
    warmup_steps: 5000
    warmup_patience: 3
    patience: 2
    factor: 0.7
    mode: min
