batch_size: 64
accum_grad: 64
max_epoch: 2000
patience: 20
# The initialization method for model parameters
init: xavier_uniform

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.4
    positional_dropout_rate: 0.4
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.4
    positional_dropout_rate: 0.4
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

e2e_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.05
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 60000
